-- ============================================================================
-- FERRE INTER - ACTUALIZACIÓN DE ESQUEMA & INVENTARIO MAESTRO (67 PRODUCTOS)
-- ============================================================================

-- 1. Asegurar columnas de inventario avanzado en public.products
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS wholesale_price NUMERIC(12, 2);
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_warehouse INT DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_store INT DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock_online INT DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS warranty TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS dimensions TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS materials TEXT;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS inventory_status TEXT DEFAULT 'Disponible';

-- 2. Asegurar Storage Bucket 'products' para fotos
INSERT INTO storage.buckets (id, name, public)
VALUES ('products', 'products', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Políticas de lectura y subida pública para fotos
DO 37692
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Products' AND tablename = 'objects') THEN
    CREATE POLICY "Public Access Products" ON storage.objects FOR SELECT USING (bucket_id = 'products');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Upload Products' AND tablename = 'objects') THEN
    CREATE POLICY "Public Upload Products" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'products');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Products' AND tablename = 'objects') THEN
    CREATE POLICY "Public Update Products" ON storage.objects FOR UPDATE USING (bucket_id = 'products');
  END IF;
END 37692;

-- 3. Carga e inserción de los 67 productos reales de inventario
INSERT INTO public.products (
  sku,
  name,
  slug,
  brand,
  category,
  price,
  discount_price,
  wholesale_price,
  stock_qty,
  stock_warehouse,
  stock_store,
  stock_online,
  warranty,
  dimensions,
  materials,
  inventory_status,
  description,
  images,
  is_featured,
  is_active
)
VALUES
  ('KD4', 'Bisagra Parche Inoxidable 304', 'bisagra-parche-inoxidable-304-kd4', 'FERREINTER', 'bisagras', 7800.0, NULL, 6700.0, 1000, 400, 200, 400, '10 AÑOS', '35MM', 'ACERO INOX 304', 'PRIVADO', 'Bisagra tipo parche de 35 mm, fabricada en acero inoxidable 304. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], true, true),
  ('KD5', 'Bisagra Semiparche Inoxidable 304', 'bisagra-semiparche-inoxidable-304-kd5', 'FERREINTER', 'bisagras', 7800.0, NULL, 6700.0, 1000, 400, 400, 200, '10 AÑOS', '35MM', 'ACERO INOX 304', 'PRIVADO', 'Bisagra tipo semiparche de 35 mm, fabricada en acero inoxidable 304. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], true, true),
  ('KD6', 'Bisagra Superacodada Inoxidable 304', 'bisagra-superacodada-inoxidable-304-kd6', 'FERREINTER', 'bisagras', 7800.0, NULL, 6700.0, 1000, 400, 200, 400, '10 AÑOS', '35MM', 'ACERO INOX 304', 'PRIVADO', 'Bisagra tipo superacodada de 35 mm, fabricada en acero inoxidable 304. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], true, true),
  ('HBM550-01', 'Bisagra Parche Cierre Lento 304 Negra', 'bisagra-parche-cierre-lento-304-negra-hbm550-01', 'FERREINTER', 'bisagras', 7800.0, NULL, 6700.0, 1000, 400, 200, 400, '10 AÑOS', '35MM', 'ACERO ZINCADO', 'PRIVADO', 'Bisagra tipo parche de 35 mm, con acabado negro. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.', ARRAY['/dewalt-chopsaw.jpg'], true, true),
  ('HBM550-02', 'Bisagra Semiparche Cierre Lento 304 Negra', 'bisagra-semiparche-cierre-lento-304-negra-hbm550-02', 'FERREINTER', 'bisagras', 7800.0, NULL, 6700.0, 1000, 400, 200, 400, '10 AÑOS', '35MM', 'ACERO ZINCADO', 'PRIVADO', 'Bisagra tipo semiparche de 35 mm, con acabado negro. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.', ARRAY['/dewalt-chopsaw.jpg'], true, true),
  ('MT317', 'Bisagra Parche Cierre Lento', 'bisagra-parche-cierre-lento-mt317', 'FERREINTER', 'bisagras', 2700.0, NULL, 2450.0, 1000, 400, 200, 400, '1 AÑO', '35MM', 'ACERO ZINCADO', 'PRIVADO', 'Bisagra tipo parche de 35 mm, fabricada en acero zincado. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.', ARRAY['/dewalt-chopsaw.jpg'], true, true),
  ('MT318', 'Bisagra Semiparche Cierre Lento', 'bisagra-semiparche-cierre-lento-mt318', 'FERREINTER', 'bisagras', 2700.0, NULL, 2450.0, 1000, 400, 200, 400, '1 AÑO', '35MM', 'ACERO ZINCADO', 'PRIVADO', 'Bisagra tipo semiparche de 35 mm, fabricada en acero zincado. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('FGV', 'Bisagra Superacodada Cierre Lento', 'bisagra-superacodada-cierre-lento-fgv', 'FERREINTER', 'bisagras', 2700.0, NULL, 2650.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo superacodada. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('MTR', 'Bisagra Parche Sencilla', 'bisagra-parche-sencilla-mtr', 'FERREINTER', 'bisagras', 1750.0, NULL, 1600.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo parche. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('MTA', 'Bisagra Semiparche Sencilla', 'bisagra-semiparche-sencilla-mta', 'FERREINTER', 'bisagras', 1750.0, NULL, 1600.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo semiparche. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('FGV-2', 'Bisagra Superacodada Sencilla', 'bisagra-superacodada-sencilla-fgv-2', 'FERREINTER', 'bisagras', 1750.0, NULL, 1800.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo superacodada. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('1B2', 'Bisagra Nudo Inoxidable 2 Pulgadas', 'bisagra-nudo-inoxidable-2-pulgadas-1b2', 'FERREINTER', 'bisagras', 2800.0, NULL, 2450.0, 1000, 400, 200, 400, '1 AÑO', '2 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra de nudo de 2 pulgadas, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('1B3', 'Bisagra Nudo Inoxidable 3 Pulgadas', 'bisagra-nudo-inoxidable-3-pulgadas-1b3', 'FERREINTER', 'bisagras', 3000.0, NULL, 2650.0, 1000, 400, 200, 400, '1 AÑO', '3 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra de nudo de 3 pulgadas, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('HY833', 'Bisagra Omega 3X3 Zinc', 'bisagra-omega-3x3-zinc-hy833', 'FERREINTER', 'bisagras', 1800.0, NULL, 1650.0, 1000, 400, 200, 400, '1 AÑO', '3 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra tipo omega, referencia 3 × 3. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('HY833N', 'Bisagra Omega 3X3 Negra', 'bisagra-omega-3x3-negra-hy833n', 'FERREINTER', 'bisagras', 1900.0, NULL, 1800.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo omega, referencia 3 × 3, con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('DY0023', 'Bisagra Nudo 4X3 Inoxidable', 'bisagra-nudo-4x3-inoxidable-dy0023', 'FERREINTER', 'bisagras', 7200.0, NULL, 6500.0, 1000, 400, 200, 400, '1 AÑO', '4 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra de nudo, referencia 4 × 3, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0037', 'Bisagra Nudo 4X3 Negro Inoxidable', 'bisagra-nudo-4x3-negro-inoxidable-ip0037', 'FERREINTER', 'bisagras', 7400.0, NULL, 6800.0, 1000, 400, 200, 400, '1 AÑO', '4 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra de nudo, referencia 4 × 3, fabricada en acero inoxidable y con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('FK00058', 'Bisagra Omega 4X3 Inoxidable', 'bisagra-omega-4x3-inoxidable-fk00058', 'FERREINTER', 'bisagras', 10500.0, NULL, 9200.0, 1000, 400, 200, 400, '1 AÑO', '4 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra tipo omega, referencia 4 × 3, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('FK00058-2', 'Bisagra Omega 4X3 Negro Inoxidable', 'bisagra-omega-4x3-negro-inoxidable-fk00058-2', 'FERREINTER', 'bisagras', 10500.0, NULL, 9200.0, 1000, 400, 200, 400, '1 AÑO', '4 PULGADAS', 'ACERO INOX', 'PRIVADO', 'Bisagra tipo omega, referencia 4 × 3, fabricada en acero inoxidable y con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('114457', 'Bisagra Doble Accion Oeste', 'bisagra-doble-accion-oeste-114457', 'FERREINTER', 'bisagras', 21800.0, NULL, 17000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra de doble acción tipo oeste. Diseñada para puertas batientes que requieren apertura en ambos sentidos. Su doble acción permite el movimiento de la puerta hacia uno u otro lado, facilitando el paso entre espacios.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('HC3627', 'Bisagra De Golpe', 'bisagra-de-golpe-hc3627', 'FERREINTER', 'bisagras', 1800.0, NULL, 1650.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra de golpe. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0034', 'Bisagra Cierra Puerta 4X3 Omega', 'bisagra-cierra-puerta-4x3-omega-ip0034', 'FERREINTER', 'bisagras', 33000.0, NULL, 28000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra cierrapuertas tipo omega, referencia 4 × 3. Diseñada para puertas que requieren una bisagra con función de cierre. Combina el movimiento de apertura con la función cierrapuertas en un mismo herraje.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0035', 'Bisagra Cierra Puerta 4X3 Nudo', 'bisagra-cierra-puerta-4x3-nudo-ip0035', 'FERREINTER', 'bisagras', 58000.0, NULL, 49000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra cierrapuertas de nudo, referencia 4 × 3. Diseñada para puertas que requieren una bisagra con función de cierre. Combina el movimiento de apertura con la función cierrapuertas en un mismo herraje.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('HYS-00056N', 'Bisagra Omega 3X1 Negra Acero Inox', 'bisagra-omega-3x1-negra-acero-inox-hys-00056n', 'FERREINTER', 'bisagras', 5500.0, NULL, 4400.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo omega, referencia 3 × 1, fabricada en acero inoxidable y con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('FK00056', 'Bisagra Omega 3X1 Acero Inox', 'bisagra-omega-3x1-acero-inox-fk00056', 'FERREINTER', 'bisagras', 5500.0, NULL, 4400.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo omega, referencia 3 × 1, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('HYS-0131', 'Placa Para Reparacion De Bisagras', 'placa-para-reparacion-de-bisagras-hys-0131', 'FERREINTER', 'placas-reparacion', 2000.0, NULL, 1800.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Placa para reparación de bisagras, diseñada para trabajos de mantenimiento en puertas de muebles y gabinetes. Sirve como apoyo en la zona de fijación de la bisagra y facilita la recuperación del punto de montaje cuando requiere reparación.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('FR5521', 'Bisagra Maquina', 'bisagra-maquina-fr5521', 'FERREINTER', 'bisagras', 2500.0, NULL, 2200.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo máquina. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('4365', 'Bisagra Robocop Sencilla', 'bisagra-robocop-sencilla-4365', 'FERREINTER', 'bisagras', 11000.0, NULL, 9500.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo Robocop sencilla. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('4366', 'Bisagra Robocop Cierre Lento', 'bisagra-robocop-cierre-lento-4366', 'FERREINTER', 'bisagras', 18000.0, NULL, 16500.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Bisagra tipo Robocop con cierre lento. Diseñada para puertas de muebles y trabajos de carpintería. Su sistema de cierre lento suaviza el movimiento al cerrar y ofrece una operación práctica en el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('587SS', 'Chapa Pomo Cromada Alcoba', 'chapa-pomo-cromada-alcoba-587ss', 'LOCK PRIME', 'chapas', 13500.0, NULL, 12000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura tipo pomo, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su pomo permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('BK587', 'Chapa Pomo Cromada Baño', 'chapa-pomo-cromada-ba-o-bk587', 'LOCK PRIME', 'chapas', 13500.0, NULL, 12000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura tipo pomo, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su pomo permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('LP007', 'Chapa Manija Cuadrada Cromada Alcoba', 'chapa-manija-cuadrada-cromada-alcoba-lp007', 'LOCK PRIME', 'chapas', 49900.0, NULL, 47000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cuadrada, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('LP008', 'Chapa Manija Cuadrada Cromada Baño', 'chapa-manija-cuadrada-cromada-ba-o-lp008', 'LOCK PRIME', 'chapas', 49900.0, NULL, 47000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cuadrada, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('LP003', 'Chapa Manija Cilindrica Cromada Alcoba', 'chapa-manija-cilindrica-cromada-alcoba-lp003', 'LOCK PRIME', 'chapas', 27000.0, NULL, 24000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cilíndrica, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('LP005', 'Chapa Manija Cilindrica Cromada Baño', 'chapa-manija-cilindrica-cromada-ba-o-lp005', 'LOCK PRIME', 'chapas', 27000.0, NULL, 24000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cilíndrica, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('LP004', 'Chapa Manija Cilindrica Negra Alcoba', 'chapa-manija-cilindrica-negra-alcoba-lp004', 'LOCK PRIME', 'chapas', 27000.0, NULL, 24000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cilíndrica, con acabado negro, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('LP006', 'Chapa Manija Cilindrica Negra Baño', 'chapa-manija-cilindrica-negra-ba-o-lp006', 'LOCK PRIME', 'chapas', 27000.0, NULL, 24000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cilíndrica, con acabado negro, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('S138', 'Chapa Manija Clindrica Cromada Entrada P', 'chapa-manija-clindrica-cromada-entrada-p-s138', 'PANTHERS', 'chapas', 27000.0, NULL, 24000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cilíndrica, con acabado cromado, de la marca PANTHERS. Diseñada para puertas de entrada. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('S139', 'Chapa Manija Cilindrica Negra Entrada P', 'chapa-manija-cilindrica-negra-entrada-p-s139', 'PANTHERS', 'chapas', 27000.0, NULL, 24000.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura con manija cilíndrica, con acabado negro, de la marca PANTHERS. Diseñada para puertas de entrada. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('KL1080', 'Cerradura Sobreponer 1080', 'cerradura-sobreponer-1080-kl1080', 'KL', 'chapas', 146000.0, NULL, 135780.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura de sobreponer modelo 1080 de la marca KL. Diseñada para instalación sobrepuesta en puertas. Su configuración permite incorporar el mecanismo de cierre sobre la superficie de la puerta y facilita su operación cotidiana.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('KL1060', 'Cerradura Sobreponer 1060', 'cerradura-sobreponer-1060-kl1060', 'KL', 'chapas', 123300.0, NULL, 114669.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura de sobreponer modelo 1060 de la marca KL. Diseñada para instalación sobrepuesta en puertas. Su configuración permite incorporar el mecanismo de cierre sobre la superficie de la puerta y facilita su operación cotidiana.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('S21', 'Cerradura Super21', 'cerradura-super21-s21', 'GATO', 'chapas', 40900.0, NULL, 38037.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura Super21 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('M64', 'Cerradura Master 64', 'cerradura-master-64-m64', 'GATO', 'chapas', 41400.0, NULL, 38502.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura Master 64 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('M65', 'Cerradura Master 65', 'cerradura-master-65-m65', 'GATO', 'chapas', 41900.0, NULL, 38967.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura Master 65 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('861', 'Cerradura Fortaleza 861', 'cerradura-fortaleza-861-861', 'GATO', 'chapas', 62300.0, NULL, 57939.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura Fortaleza 861 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('777', 'Cerradura Tipo Candado', 'cerradura-tipo-candado-777', 'GATO', 'chapas', 137000.0, NULL, 127410.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura tipo candado de la marca Gato. Diseñada para aplicaciones que requieren un cierre tipo candado. Permite asegurar el punto de cierre y ofrece una solución funcional para controlar la apertura.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('865', 'Cerradura Reja Automatica', 'cerradura-reja-automatica-865', 'GATO', 'chapas', 64000.0, NULL, 59520.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', 'Cerradura automática para reja de la marca Gato. Diseñada para el cierre de rejas. Su funcionamiento automático facilita el aseguramiento de la reja al cerrar y ofrece una solución práctica para el control de acceso.', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('728907', 'Combo Grecia Negro', 'combo-grecia-negro-728907', 'FERREINTER', 'chapas', 126600.0, NULL, 117738.0, 1000, 400, 200, 400, '1 AÑO', NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('728901', 'Combo Grecia Cromo', 'combo-grecia-cromo-728901', 'FERREINTER', 'chapas', 126600.0, NULL, 117738.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-43', 'Broca Multiproposito 5/32', 'broca-multiproposito-5-32-709-43', 'FERREINTER', 'brocas-accesorios', 8900.0, NULL, 7565.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-44', 'Broca Multiproposito 3/16', 'broca-multiproposito-3-16-709-44', 'FERREINTER', 'brocas-accesorios', 9200.0, NULL, 7820.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-45', 'Broca Multiproposito 1/4', 'broca-multiproposito-1-4-709-45', 'FERREINTER', 'brocas-accesorios', 9500.0, NULL, 8075.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('AV011', 'Prensa Resorte 3"', 'prensa-resorte-3-av011', 'FERREINTER', 'prensas-fijacion', 9900.0, NULL, 8415.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('AV012', 'Presa Resorte 6"', 'presa-resorte-6-av012', 'FERREINTER', 'prensas-fijacion', 15900.0, NULL, 13515.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('AV013', 'Prensa Resorte 9"', 'prensa-resorte-9-av013', 'FERREINTER', 'prensas-fijacion', 21000.0, NULL, 17850.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-34', 'Disco Corte Madera 10" X 40 Dientes', 'disco-corte-madera-10-x-40-dientes-709-34', 'FERREINTER', 'discos-corte', 85000.0, NULL, 72250.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-35', 'Disco Corte Madera 10" X 60 Dientes', 'disco-corte-madera-10-x-60-dientes-709-35', 'FERREINTER', 'discos-corte', 98000.0, NULL, 83300.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-36', 'Disco Corte Aluminio Madera 10" X 80 Dientes', 'disco-corte-aluminio-madera-10-x-80-dientes-709-36', 'FERREINTER', 'discos-corte', 145000.0, NULL, 123250.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-37', 'Disco Corte Aluminio Madera 10" X 100 Dientes', 'disco-corte-aluminio-madera-10-x-100-dientes-709-37', 'FERREINTER', 'discos-corte', 155000.0, NULL, 131750.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('709-38', 'Disco Corte Aluminio Madera 10" X 120 Dientes', 'disco-corte-aluminio-madera-10-x-120-dientes-709-38', 'FERREINTER', 'discos-corte', 165000.0, NULL, 140250.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0053', 'Disco Corte Madera Multiproposito 41/2 O Pulidora', 'disco-corte-madera-multiproposito-41-2-o-pulidora-ip0053', 'FERREINTER', 'discos-corte', 13900.0, NULL, 11815.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0053-1', 'Disco Corte Madera Multiproposito 7 1/4 O Radial', 'disco-corte-madera-multiproposito-7-1-4-o-radial-ip0053-1', 'FERREINTER', 'discos-corte', 39900.0, NULL, 33915.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0025', 'Escuadra 7" Profesional Carpintero', 'escuadra-7-profesional-carpintero-ip0025', 'FERREINTER', 'escuadras-medicion', 19900.0, NULL, 16915.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('IP0025-1', 'Escuadra 12" Profesional Carpintero', 'escuadra-12-profesional-carpintero-ip0025-1', 'FERREINTER', 'escuadras-medicion', 49900.0, NULL, 42415.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('2907', 'Topes Para Brocas De 1/8 A 5/8', 'topes-para-brocas-de-1-8-a-5-8-2907', 'FERREINTER', 'brocas-accesorios', 9900.0, NULL, 8415.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('S112', 'Soporte Para Broca De Mortajar Cuadrada', 'soporte-para-broca-de-mortajar-cuadrada-s112', 'FERREINTER', 'herrajes-carpinteria', 79900.0, NULL, 67915.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true),
  ('S110', 'Prensas Frente Cajon', 'prensas-frente-cajon-s110', 'FERREINTER', 'prensas-fijacion', 79900.0, NULL, 67915.0, 1000, 400, 200, 400, NULL, NULL, NULL, 'PRIVADO', '', ARRAY['/dewalt-chopsaw.jpg'], false, true)
ON CONFLICT (sku) DO UPDATE SET
  name = EXCLUDED.name,
  brand = EXCLUDED.brand,
  category = EXCLUDED.category,
  price = EXCLUDED.price,
  discount_price = EXCLUDED.discount_price,
  wholesale_price = EXCLUDED.wholesale_price,
  stock_qty = EXCLUDED.stock_qty,
  stock_warehouse = EXCLUDED.stock_warehouse,
  stock_store = EXCLUDED.stock_store,
  stock_online = EXCLUDED.stock_online,
  warranty = EXCLUDED.warranty,
  dimensions = EXCLUDED.dimensions,
  materials = EXCLUDED.materials,
  inventory_status = EXCLUDED.inventory_status,
  description = EXCLUDED.description;
