import { Product } from "../types";

export const INITIAL_REAL_PRODUCTS: Product[] = [
  {
    "id": "prod-001",
    "sku": "KD4",
    "name": "Bisagra Parche Inoxidable 304",
    "slug": "bisagra-parche-inoxidable-304-kd4",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7800.0,
    "discount_price": null,
    "wholesale_price": 6700.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "10 AÑOS",
    "dimensions": "35MM",
    "materials": "ACERO INOX 304",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo parche de 35 mm, fabricada en acero inoxidable 304. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": true,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 12,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-002",
    "sku": "KD5",
    "name": "Bisagra Semiparche Inoxidable 304",
    "slug": "bisagra-semiparche-inoxidable-304-kd5",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7800.0,
    "discount_price": null,
    "wholesale_price": 6700.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 400,
    "stock_online": 200,
    "warranty": "10 AÑOS",
    "dimensions": "35MM",
    "materials": "ACERO INOX 304",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo semiparche de 35 mm, fabricada en acero inoxidable 304. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": true,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 13,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-003",
    "sku": "KD6",
    "name": "Bisagra Superacodada Inoxidable 304",
    "slug": "bisagra-superacodada-inoxidable-304-kd6",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7800.0,
    "discount_price": null,
    "wholesale_price": 6700.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "10 AÑOS",
    "dimensions": "35MM",
    "materials": "ACERO INOX 304",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo superacodada de 35 mm, fabricada en acero inoxidable 304. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": true,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 14,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-004",
    "sku": "HBM550-01",
    "name": "Bisagra Parche Cierre Lento 304 Negra",
    "slug": "bisagra-parche-cierre-lento-304-negra-hbm550-01",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7800.0,
    "discount_price": null,
    "wholesale_price": 6700.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "10 AÑOS",
    "dimensions": "35MM",
    "materials": "ACERO ZINCADO",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo parche de 35 mm, con acabado negro. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": true,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 15,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-005",
    "sku": "HBM550-02",
    "name": "Bisagra Semiparche Cierre Lento 304 Negra",
    "slug": "bisagra-semiparche-cierre-lento-304-negra-hbm550-02",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7800.0,
    "discount_price": null,
    "wholesale_price": 6700.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "10 AÑOS",
    "dimensions": "35MM",
    "materials": "ACERO ZINCADO",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo semiparche de 35 mm, con acabado negro. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": true,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 16,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-006",
    "sku": "MT317",
    "name": "Bisagra Parche Cierre Lento",
    "slug": "bisagra-parche-cierre-lento-mt317",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 2700.0,
    "discount_price": null,
    "wholesale_price": 2450.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "35MM",
    "materials": "ACERO ZINCADO",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo parche de 35 mm, fabricada en acero zincado. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": true,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 17,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-007",
    "sku": "MT318",
    "name": "Bisagra Semiparche Cierre Lento",
    "slug": "bisagra-semiparche-cierre-lento-mt318",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 2700.0,
    "discount_price": null,
    "wholesale_price": 2450.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "35MM",
    "materials": "ACERO ZINCADO",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo semiparche de 35 mm, fabricada en acero zincado. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 18,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-008",
    "sku": "FGV",
    "name": "Bisagra Superacodada Cierre Lento",
    "slug": "bisagra-superacodada-cierre-lento-fgv",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 2700.0,
    "discount_price": null,
    "wholesale_price": 2650.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo superacodada. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su sistema de cierre lento permite un movimiento suave al cerrar la puerta y su configuración facilita la elección del herraje según la disposición del mueble.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 19,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-009",
    "sku": "MTR",
    "name": "Bisagra Parche Sencilla",
    "slug": "bisagra-parche-sencilla-mtr",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 1750.0,
    "discount_price": null,
    "wholesale_price": 1600.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo parche. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 20,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-010",
    "sku": "MTA",
    "name": "Bisagra Semiparche Sencilla",
    "slug": "bisagra-semiparche-sencilla-mta",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 1750.0,
    "discount_price": null,
    "wholesale_price": 1600.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo semiparche. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 21,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-011",
    "sku": "FGV-2",
    "name": "Bisagra Superacodada Sencilla",
    "slug": "bisagra-superacodada-sencilla-fgv-2",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 1750.0,
    "discount_price": null,
    "wholesale_price": 1800.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo superacodada. Diseñada para puertas de muebles, gabinetes, clósets y trabajos de carpintería. Su configuración permite seleccionar el herraje según la disposición de la puerta, facilitando su apertura y cierre en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 22,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-012",
    "sku": "1B2",
    "name": "Bisagra Nudo Inoxidable 2 Pulgadas",
    "slug": "bisagra-nudo-inoxidable-2-pulgadas-1b2",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 2800.0,
    "discount_price": null,
    "wholesale_price": 2450.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "2 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra de nudo de 2 pulgadas, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 23,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-013",
    "sku": "1B3",
    "name": "Bisagra Nudo Inoxidable 3 Pulgadas",
    "slug": "bisagra-nudo-inoxidable-3-pulgadas-1b3",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 3000.0,
    "discount_price": null,
    "wholesale_price": 2650.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "3 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra de nudo de 3 pulgadas, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 24,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-014",
    "sku": "HY833",
    "name": "Bisagra Omega 3X3 Zinc",
    "slug": "bisagra-omega-3x3-zinc-hy833",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 1800.0,
    "discount_price": null,
    "wholesale_price": 1650.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "3 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo omega, referencia 3 × 3. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 25,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-015",
    "sku": "HY833N",
    "name": "Bisagra Omega 3X3 Negra",
    "slug": "bisagra-omega-3x3-negra-hy833n",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 1900.0,
    "discount_price": null,
    "wholesale_price": 1800.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo omega, referencia 3 × 3, con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 26,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-016",
    "sku": "DY0023",
    "name": "Bisagra Nudo 4X3 Inoxidable",
    "slug": "bisagra-nudo-4x3-inoxidable-dy0023",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7200.0,
    "discount_price": null,
    "wholesale_price": 6500.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "4 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra de nudo, referencia 4 × 3, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 27,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-017",
    "sku": "IP0037",
    "name": "Bisagra Nudo 4X3 Negro Inoxidable",
    "slug": "bisagra-nudo-4x3-negro-inoxidable-ip0037",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 7400.0,
    "discount_price": null,
    "wholesale_price": 6800.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "4 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra de nudo, referencia 4 × 3, fabricada en acero inoxidable y con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 28,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-018",
    "sku": "FK00058",
    "name": "Bisagra Omega 4X3 Inoxidable",
    "slug": "bisagra-omega-4x3-inoxidable-fk00058",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 10500.0,
    "discount_price": null,
    "wholesale_price": 9200.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "4 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo omega, referencia 4 × 3, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 29,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-019",
    "sku": "FK00058-2",
    "name": "Bisagra Omega 4X3 Negro Inoxidable",
    "slug": "bisagra-omega-4x3-negro-inoxidable-fk00058-2",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 10500.0,
    "discount_price": null,
    "wholesale_price": 9200.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": "4 PULGADAS",
    "materials": "ACERO INOX",
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo omega, referencia 4 × 3, fabricada en acero inoxidable y con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 30,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-020",
    "sku": "114457",
    "name": "Bisagra Doble Accion Oeste",
    "slug": "bisagra-doble-accion-oeste-114457",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 21800.0,
    "discount_price": null,
    "wholesale_price": 17000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra de doble acción tipo oeste. Diseñada para puertas batientes que requieren apertura en ambos sentidos. Su doble acción permite el movimiento de la puerta hacia uno u otro lado, facilitando el paso entre espacios.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 31,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-021",
    "sku": "HC3627",
    "name": "Bisagra De Golpe",
    "slug": "bisagra-de-golpe-hc3627",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 1800.0,
    "discount_price": null,
    "wholesale_price": 1650.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra de golpe. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 32,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-022",
    "sku": "IP0034",
    "name": "Bisagra Cierra Puerta 4X3 Omega",
    "slug": "bisagra-cierra-puerta-4x3-omega-ip0034",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 33000.0,
    "discount_price": null,
    "wholesale_price": 28000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra cierrapuertas tipo omega, referencia 4 × 3. Diseñada para puertas que requieren una bisagra con función de cierre. Combina el movimiento de apertura con la función cierrapuertas en un mismo herraje.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 33,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-023",
    "sku": "IP0035",
    "name": "Bisagra Cierra Puerta 4X3 Nudo",
    "slug": "bisagra-cierra-puerta-4x3-nudo-ip0035",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 58000.0,
    "discount_price": null,
    "wholesale_price": 49000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra cierrapuertas de nudo, referencia 4 × 3. Diseñada para puertas que requieren una bisagra con función de cierre. Combina el movimiento de apertura con la función cierrapuertas en un mismo herraje.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 34,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-024",
    "sku": "HYS-00056N",
    "name": "Bisagra Omega 3X1 Negra Acero Inox",
    "slug": "bisagra-omega-3x1-negra-acero-inox-hys-00056n",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 5500.0,
    "discount_price": null,
    "wholesale_price": 4400.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo omega, referencia 3 × 1, fabricada en acero inoxidable y con acabado negro. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 35,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-025",
    "sku": "FK00056",
    "name": "Bisagra Omega 3X1 Acero Inox",
    "slug": "bisagra-omega-3x1-acero-inox-fk00056",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 5500.0,
    "discount_price": null,
    "wholesale_price": 4400.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo omega, referencia 3 × 1, fabricada en acero inoxidable. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 36,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-026",
    "sku": "HYS-0131",
    "name": "Placa Para Reparacion De Bisagras",
    "slug": "placa-para-reparacion-de-bisagras-hys-0131",
    "brand": "FERREINTER",
    "category": "placas-reparacion",
    "price": 2000.0,
    "discount_price": null,
    "wholesale_price": 1800.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Placa para reparación de bisagras, diseñada para trabajos de mantenimiento en puertas de muebles y gabinetes. Sirve como apoyo en la zona de fijación de la bisagra y facilita la recuperación del punto de montaje cuando requiere reparación.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 12,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-027",
    "sku": "FR5521",
    "name": "Bisagra Maquina",
    "slug": "bisagra-maquina-fr5521",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 2500.0,
    "discount_price": null,
    "wholesale_price": 2200.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo máquina. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 13,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-028",
    "sku": "4365",
    "name": "Bisagra Robocop Sencilla",
    "slug": "bisagra-robocop-sencilla-4365",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 11000.0,
    "discount_price": null,
    "wholesale_price": 9500.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo Robocop sencilla. Diseñada para la articulación de puertas y trabajos de carpintería compatibles con este tipo de herraje. Permite unir la hoja con su soporte y facilitar el movimiento de apertura y cierre.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 14,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-029",
    "sku": "4366",
    "name": "Bisagra Robocop Cierre Lento",
    "slug": "bisagra-robocop-cierre-lento-4366",
    "brand": "FERREINTER",
    "category": "bisagras",
    "price": 18000.0,
    "discount_price": null,
    "wholesale_price": 16500.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Bisagra tipo Robocop con cierre lento. Diseñada para puertas de muebles y trabajos de carpintería. Su sistema de cierre lento suaviza el movimiento al cerrar y ofrece una operación práctica en el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 15,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-030",
    "sku": "587SS",
    "name": "Chapa Pomo Cromada Alcoba",
    "slug": "chapa-pomo-cromada-alcoba-587ss",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 13500.0,
    "discount_price": null,
    "wholesale_price": 12000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura tipo pomo, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su pomo permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 16,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-031",
    "sku": "BK587",
    "name": "Chapa Pomo Cromada Baño",
    "slug": "chapa-pomo-cromada-ba-o-bk587",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 13500.0,
    "discount_price": null,
    "wholesale_price": 12000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura tipo pomo, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su pomo permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 17,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-032",
    "sku": "LP007",
    "name": "Chapa Manija Cuadrada Cromada Alcoba",
    "slug": "chapa-manija-cuadrada-cromada-alcoba-lp007",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 49900.0,
    "discount_price": null,
    "wholesale_price": 47000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cuadrada, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 18,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-033",
    "sku": "LP008",
    "name": "Chapa Manija Cuadrada Cromada Baño",
    "slug": "chapa-manija-cuadrada-cromada-ba-o-lp008",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 49900.0,
    "discount_price": null,
    "wholesale_price": 47000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cuadrada, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 19,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-034",
    "sku": "LP003",
    "name": "Chapa Manija Cilindrica Cromada Alcoba",
    "slug": "chapa-manija-cilindrica-cromada-alcoba-lp003",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 27000.0,
    "discount_price": null,
    "wholesale_price": 24000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cilíndrica, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 20,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-035",
    "sku": "LP005",
    "name": "Chapa Manija Cilindrica Cromada Baño",
    "slug": "chapa-manija-cilindrica-cromada-ba-o-lp005",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 27000.0,
    "discount_price": null,
    "wholesale_price": 24000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cilíndrica, con acabado cromado, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 21,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-036",
    "sku": "LP004",
    "name": "Chapa Manija Cilindrica Negra Alcoba",
    "slug": "chapa-manija-cilindrica-negra-alcoba-lp004",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 27000.0,
    "discount_price": null,
    "wholesale_price": 24000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cilíndrica, con acabado negro, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 22,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-037",
    "sku": "LP006",
    "name": "Chapa Manija Cilindrica Negra Baño",
    "slug": "chapa-manija-cilindrica-negra-ba-o-lp006",
    "brand": "LOCK PRIME",
    "category": "chapas",
    "price": 27000.0,
    "discount_price": null,
    "wholesale_price": 24000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cilíndrica, con acabado negro, de la marca LOCK PRIME. Diseñada para puertas de baño. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 23,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-038",
    "sku": "S138",
    "name": "Chapa Manija Clindrica Cromada Entrada P",
    "slug": "chapa-manija-clindrica-cromada-entrada-p-s138",
    "brand": "PANTHERS",
    "category": "chapas",
    "price": 27000.0,
    "discount_price": null,
    "wholesale_price": 24000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cilíndrica, con acabado cromado, de la marca PANTHERS. Diseñada para puertas de entrada. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 24,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-039",
    "sku": "S139",
    "name": "Chapa Manija Cilindrica Negra Entrada P",
    "slug": "chapa-manija-cilindrica-negra-entrada-p-s139",
    "brand": "PANTHERS",
    "category": "chapas",
    "price": 27000.0,
    "discount_price": null,
    "wholesale_price": 24000.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura con manija cilíndrica, con acabado negro, de la marca PANTHERS. Diseñada para puertas de entrada. Su manija permite accionar la cerradura y facilita la apertura y el cierre de la puerta, integrando una solución funcional con un acabado que complementa el espacio.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 25,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-040",
    "sku": "KL1080",
    "name": "Cerradura Sobreponer 1080",
    "slug": "cerradura-sobreponer-1080-kl1080",
    "brand": "KL",
    "category": "chapas",
    "price": 146000.0,
    "discount_price": null,
    "wholesale_price": 135780.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura de sobreponer modelo 1080 de la marca KL. Diseñada para instalación sobrepuesta en puertas. Su configuración permite incorporar el mecanismo de cierre sobre la superficie de la puerta y facilita su operación cotidiana.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 26,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-041",
    "sku": "KL1060",
    "name": "Cerradura Sobreponer 1060",
    "slug": "cerradura-sobreponer-1060-kl1060",
    "brand": "KL",
    "category": "chapas",
    "price": 123300.0,
    "discount_price": null,
    "wholesale_price": 114669.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura de sobreponer modelo 1060 de la marca KL. Diseñada para instalación sobrepuesta en puertas. Su configuración permite incorporar el mecanismo de cierre sobre la superficie de la puerta y facilita su operación cotidiana.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 27,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-042",
    "sku": "S21",
    "name": "Cerradura Super21",
    "slug": "cerradura-super21-s21",
    "brand": "GATO",
    "category": "chapas",
    "price": 40900.0,
    "discount_price": null,
    "wholesale_price": 38037.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura Super21 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 28,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-043",
    "sku": "M64",
    "name": "Cerradura Master 64",
    "slug": "cerradura-master-64-m64",
    "brand": "GATO",
    "category": "chapas",
    "price": 41400.0,
    "discount_price": null,
    "wholesale_price": 38502.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura Master 64 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 29,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-044",
    "sku": "M65",
    "name": "Cerradura Master 65",
    "slug": "cerradura-master-65-m65",
    "brand": "GATO",
    "category": "chapas",
    "price": 41900.0,
    "discount_price": null,
    "wholesale_price": 38967.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura Master 65 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 30,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-045",
    "sku": "861",
    "name": "Cerradura Fortaleza 861",
    "slug": "cerradura-fortaleza-861-861",
    "brand": "GATO",
    "category": "chapas",
    "price": 62300.0,
    "discount_price": null,
    "wholesale_price": 57939.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura Fortaleza 861 de la marca Gato. Diseñada para asegurar puertas en aplicaciones compatibles con su configuración. Permite controlar la apertura y el cierre, ofreciendo una solución funcional para el uso cotidiano.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 31,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-046",
    "sku": "777",
    "name": "Cerradura Tipo Candado",
    "slug": "cerradura-tipo-candado-777",
    "brand": "GATO",
    "category": "chapas",
    "price": 137000.0,
    "discount_price": null,
    "wholesale_price": 127410.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura tipo candado de la marca Gato. Diseñada para aplicaciones que requieren un cierre tipo candado. Permite asegurar el punto de cierre y ofrece una solución funcional para controlar la apertura.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 32,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-047",
    "sku": "865",
    "name": "Cerradura Reja Automatica",
    "slug": "cerradura-reja-automatica-865",
    "brand": "GATO",
    "category": "chapas",
    "price": 64000.0,
    "discount_price": null,
    "wholesale_price": 59520.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "Cerradura automática para reja de la marca Gato. Diseñada para el cierre de rejas. Su funcionamiento automático facilita el aseguramiento de la reja al cerrar y ofrece una solución práctica para el control de acceso.",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 33,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-048",
    "sku": "728907",
    "name": "Combo Grecia Negro",
    "slug": "combo-grecia-negro-728907",
    "brand": "FERREINTER",
    "category": "chapas",
    "price": 126600.0,
    "discount_price": null,
    "wholesale_price": 117738.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": "1 AÑO",
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 34,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-049",
    "sku": "728901",
    "name": "Combo Grecia Cromo",
    "slug": "combo-grecia-cromo-728901",
    "brand": "FERREINTER",
    "category": "chapas",
    "price": 126600.0,
    "discount_price": null,
    "wholesale_price": 117738.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 35,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-050",
    "sku": "709-43",
    "name": "Broca Multiproposito 5/32",
    "slug": "broca-multiproposito-5-32-709-43",
    "brand": "FERREINTER",
    "category": "brocas-accesorios",
    "price": 8900.0,
    "discount_price": null,
    "wholesale_price": 7565.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 36,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-051",
    "sku": "709-44",
    "name": "Broca Multiproposito 3/16",
    "slug": "broca-multiproposito-3-16-709-44",
    "brand": "FERREINTER",
    "category": "brocas-accesorios",
    "price": 9200.0,
    "discount_price": null,
    "wholesale_price": 7820.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 12,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-052",
    "sku": "709-45",
    "name": "Broca Multiproposito 1/4",
    "slug": "broca-multiproposito-1-4-709-45",
    "brand": "FERREINTER",
    "category": "brocas-accesorios",
    "price": 9500.0,
    "discount_price": null,
    "wholesale_price": 8075.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 13,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-053",
    "sku": "AV011",
    "name": "Prensa Resorte 3\"",
    "slug": "prensa-resorte-3-av011",
    "brand": "FERREINTER",
    "category": "prensas-fijacion",
    "price": 9900.0,
    "discount_price": null,
    "wholesale_price": 8415.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 14,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-054",
    "sku": "AV012",
    "name": "Presa Resorte 6\"",
    "slug": "presa-resorte-6-av012",
    "brand": "FERREINTER",
    "category": "prensas-fijacion",
    "price": 15900.0,
    "discount_price": null,
    "wholesale_price": 13515.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 15,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-055",
    "sku": "AV013",
    "name": "Prensa Resorte 9\"",
    "slug": "prensa-resorte-9-av013",
    "brand": "FERREINTER",
    "category": "prensas-fijacion",
    "price": 21000.0,
    "discount_price": null,
    "wholesale_price": 17850.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 16,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-056",
    "sku": "709-34",
    "name": "Disco Corte Madera 10\" X 40 Dientes",
    "slug": "disco-corte-madera-10-x-40-dientes-709-34",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 85000.0,
    "discount_price": null,
    "wholesale_price": 72250.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 17,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-057",
    "sku": "709-35",
    "name": "Disco Corte Madera 10\" X 60 Dientes",
    "slug": "disco-corte-madera-10-x-60-dientes-709-35",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 98000.0,
    "discount_price": null,
    "wholesale_price": 83300.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 18,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-058",
    "sku": "709-36",
    "name": "Disco Corte Aluminio Madera 10\" X 80 Dientes",
    "slug": "disco-corte-aluminio-madera-10-x-80-dientes-709-36",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 145000.0,
    "discount_price": null,
    "wholesale_price": 123250.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 19,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-059",
    "sku": "709-37",
    "name": "Disco Corte Aluminio Madera 10\" X 100 Dientes",
    "slug": "disco-corte-aluminio-madera-10-x-100-dientes-709-37",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 155000.0,
    "discount_price": null,
    "wholesale_price": 131750.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 20,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-060",
    "sku": "709-38",
    "name": "Disco Corte Aluminio Madera 10\" X 120 Dientes",
    "slug": "disco-corte-aluminio-madera-10-x-120-dientes-709-38",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 165000.0,
    "discount_price": null,
    "wholesale_price": 140250.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 21,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-061",
    "sku": "IP0053",
    "name": "Disco Corte Madera Multiproposito 41/2 O Pulidora",
    "slug": "disco-corte-madera-multiproposito-41-2-o-pulidora-ip0053",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 13900.0,
    "discount_price": null,
    "wholesale_price": 11815.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 22,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-062",
    "sku": "IP0053-1",
    "name": "Disco Corte Madera Multiproposito 7 1/4 O Radial",
    "slug": "disco-corte-madera-multiproposito-7-1-4-o-radial-ip0053-1",
    "brand": "FERREINTER",
    "category": "discos-corte",
    "price": 39900.0,
    "discount_price": null,
    "wholesale_price": 33915.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 23,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-063",
    "sku": "IP0025",
    "name": "Escuadra 7\" Profesional Carpintero",
    "slug": "escuadra-7-profesional-carpintero-ip0025",
    "brand": "FERREINTER",
    "category": "escuadras-medicion",
    "price": 19900.0,
    "discount_price": null,
    "wholesale_price": 16915.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 24,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-064",
    "sku": "IP0025-1",
    "name": "Escuadra 12\" Profesional Carpintero",
    "slug": "escuadra-12-profesional-carpintero-ip0025-1",
    "brand": "FERREINTER",
    "category": "escuadras-medicion",
    "price": 49900.0,
    "discount_price": null,
    "wholesale_price": 42415.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 25,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-065",
    "sku": "2907",
    "name": "Topes Para Brocas De 1/8 A 5/8",
    "slug": "topes-para-brocas-de-1-8-a-5-8-2907",
    "brand": "FERREINTER",
    "category": "brocas-accesorios",
    "price": 9900.0,
    "discount_price": null,
    "wholesale_price": 8415.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 26,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-066",
    "sku": "S112",
    "name": "Soporte Para Broca De Mortajar Cuadrada",
    "slug": "soporte-para-broca-de-mortajar-cuadrada-s112",
    "brand": "FERREINTER",
    "category": "herrajes-carpinteria",
    "price": 79900.0,
    "discount_price": null,
    "wholesale_price": 67915.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 27,
    "created_at": "2026-10-01T00:00:00.000Z"
  },
  {
    "id": "prod-067",
    "sku": "S110",
    "name": "Prensas Frente Cajon",
    "slug": "prensas-frente-cajon-s110",
    "brand": "FERREINTER",
    "category": "prensas-fijacion",
    "price": 79900.0,
    "discount_price": null,
    "wholesale_price": 67915.0,
    "stock": 1000,
    "stock_warehouse": 400,
    "stock_store": 200,
    "stock_online": 400,
    "warranty": null,
    "dimensions": null,
    "materials": null,
    "inventory_status": "PRIVADO",
    "description": "",
    "images": [
      "/dewalt-chopsaw.jpg"
    ],
    "is_featured": false,
    "is_active": true,
    "rating": 5.0,
    "reviews_count": 28,
    "created_at": "2026-10-01T00:00:00.000Z"
  }
];
